version: '3.8'

services:
  bank-app:
    image: bank:v1
    build: .
    ports:
      - '3000:3000'

    environment:
      - MONGODB_URI:'mongodb://localhost:27017/transactionhistory'

    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'


